PRAGMA journal_mode = WAL;

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE,
	info TEXT,
	email TEXT UNIQUE,
	password TEXT UNIQUE,
	phoneNumber TEXT UNIQUE,
	online BOOL,
	wins INTEGER,
	defeats INTEGER
);

CREATE TABLE IF NOT EXISTS friends (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	requester_id INTEGER,
	addressee_id INTEGER,
	status TEXT CHECK(status IN ('pending', 'accepted', 'blocked')) DEFAULT 'pending',
	UNIQUE(requester_id, addressee_id),
	FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (addressee_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ChatRoom (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userId1 INTEGER,
	userId2 INTEGER,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (userId1, userId2),
	FOREIGN KEY (userId1) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (userId2) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Messages (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	chatRoomId INTEGER,
	fromId INTEGER,
	toId INTEGER,
	messageText TEXT NOT NULL,
	Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (chatRoomId) REFERENCES ChatRoom(id) ON DELETE CASCADE,
	FOREIGN KEY (fromId) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (toId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS twoFa (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userId INTEGER,
	twoFAType TEXT CHECK(twoFAType IN ('SMS', 'EMAIL', 'QR', 'disabled')) DEFAULT 'disabled',
	twoFASecret TEXT,
	createdDate INTEGER,
	expireDate INTEGER,
	status TEXT CHECK(status IN ('pending', 'enabled', 'disabled')) DEFAULT 'disabled',
	FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MatchHistory (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	winnerId INTEGER,
	loserId INTEGER,
	date INTEGER,
	FOREIGN KEY (winnerId) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (loserId) REFERENCES users(id) ON DELETE CASCADE
);
